const { Product } = require('../models');

const productdata = [
    {
        product_name: 'Washer',
        description: 'Fairly old whirlpool washer that does not currently work. I do not have the time to fix it myself.',
        img_url: 'https://content.instructables.com/ORIG/FID/4HNY/GC5ZHB93/FID4HNYGC5ZHB93.jpg?auto=webp',
        location_zipcode: '27513',
        category_id: 1,
        user_id: 1,
    },
    {
        product_name: 'Stove top',
        description: 'Used stove top. In working condition, no longer have need for it.',
        img_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUH8LWNienQvOjMP-KUF_7lE9QvAL0aDlSng&usqp=CAU',
        location_zipcode: '27607',
        category_id: 1,
        user_id: 2,
    },
    {
        product_name: 'Old A/C Unit',
        description: 'Got an old Amana A/C unit that is still in working condition.',
        img_url: 'https://cd5a26cb38e2f692acf4-1755b9e4a9778d68267568d15a55e9ec.ssl.cf2.rackcdn.com/5539bca8f3/55-1.jpg',
        location_zipcode: '27523',
        category_id: 1,
        user_id: 3,
    },
    {
        product_name: 'Radiators',
        description: 'These old radiators are just sitting in my attic. Someone come get them!',
        img_url: 'https://cdn.vox-cdn.com/thumbor/MogVo8k0wfOlSjlejnm-bnQuB-o=/0x0:1899x918/1200x800/filters:focal(798x308:1100x610)/cdn.vox-cdn.com/uploads/chorus_image/image/65889550/vintage_radiators_x_banner.0.jpg',
        location_zipcode: '27607',
        category_id: 1,
        user_id: 4,
    },
    {
        product_name: 'Couch',
        description: 'Older family couch. Has a little wear and tear, but can easily be repurposed.',
        img_url: 'https://firedawgsjunkremoval.com/wp-content/uploads/2015/02/old-sofa-removal-in-indianapolis.jpg',
        location_zipcode: '27604',
        category_id: 2,
        user_id: 5,
    },
    {
        product_name: 'Side table',
        description: 'Damaged side table with scuff marks',
        img_url: 'https://antiquesworld.co.uk/wp-content/uploads/2018/06/68551.jpg',
        location_zipcode: '27604',
        category_id: 2,
        user_id: 6,
    },
    {
        product_name: 'Old chairs',
        description: 'These older chairs just need some love to look brand new and unique.',
        img_url: 'https://wisebread-killeracesmedia.netdna-ssl.com/files/fruganomics/imagecache/605x340/blog-images/chairs-5252078-small.jpg',
        location_zipcode: '27877',
        category_id: 2,
        user_id: 7,
    },
    {
        product_name: 'Gaming Chair',
        description: "My daughter used to use this old gaming chair in high-school, but since she moved off to college and since we are trying to turn her room into an office, I don't see any need for it.",
        img_url: 'https://www.nfm.com/dw/image/v2/BDFM_PRD/on/demandware.static/-/Sites-nfm-master-catalog/default/dw4d406f23/images/053/35/53350070-1.jpg?sw=365&sh=365&sm=fit',
        location_zipcode: '28334',
        category_id: 2,
        user_id: 1,
    },
    {
        product_name: 'Gameboy Color',
        description: "Old gameboy color found in my son's room. Still works, but has no games.",
        img_url: 'https://m.media-amazon.com/images/I/81Z-VLCxlJL._SX466_.jpg',
        location_zipcode: '27602',
        category_id: 6,
        user_id: 2,
    },
    {
        product_name: 'Old TV',
        description: 'I have an old TV with a large back, one of the really old ones.',
        img_url: 'https://www.disablemycable.com/wp-content/uploads/2013/03/IMG_3483_small.jpg',
        location_zipcode: '27607',
        category_id: 3,
        user_id: 3,
    },
    {
        product_name: 'Assortment of video gaming consoles',
        description: 'This is a collection of gaming consoles that my husband has had since he was a teenager, but he never plays with them and they just collect dust so I am sure that he will not mind me getting rid of some junk.',
        img_url: 'https://www.realgear.net/wp-content/uploads/2017/08/retro-gaming-consoles-scaled.jpg',
        location_zipcode: '27223',
        category_id: 6,
        user_id: 4,
    },
    {
        product_name: 'Portable DVD player',
        description: 'Bought this portable dvd player for my grandson for Christmas last year, but never uses it and I dont know why. First come first serve.',
        img_url: 'https://u-mercari-images.mercdn.net/photos/m98210249719_1.jpg?1612654033',
        location_zipcode: '27607',
        category_id: 3,
        user_id: 5,
    },
    {
        product_name: 'Rusted Screwdrivers',
        description: 'Tin Can full of rusty screwdrivers that are no longer being used.',
        img_url: 'https://i.ytimg.com/vi/xNukg6c93vg/maxresdefault.jpg',
        location_zipcode: '27560',
        category_id: 4,
        user_id: 6,
    },
    {
        product_name: 'Axe',
        description: 'Wooden handle axe that I no longer need.',
        img_url: 'https://i.ytimg.com/vi/0STKh85ApDs/maxresdefault.jpg',
        location_zipcode: '27616',
        category_id: 4,
        user_id: 7,
    },
    {
        product_name: 'Old Power Saw',
        description: 'Got this old power saw that I want to get rid of since I bought a new one. Still works just remember to wear safety goggles!',
        img_url: 'https://diy.sndimg.com/content/dam/images/diy/fullset/2011/8/12/0/Original_Old-Circular-Saw_s4x3.jpg.rend.hgtvcom.1280.960.suffix/1420874850655.jpeg',
        location_zipcode: '27560',
        category_id: 4,
        user_id: 1,
    },
    {
        product_name: 'Spare universal remote',
        description: 'I have a spare universal remote that I want to get rid of since I bought a new TV which came with a new remote.',
        img_url: 'https://www.lg.com/us/images/tv-audio-video-accessories/md05893656/gallery/1100-1.jpg',
        location_zipcode: '27510',
        category_id: 3,
        user_id: 2,
    },
    {
        product_name: 'Power Drills',
        description: "Don't need these old drills anymore. If they aren't gone in 1 week then I'm just gonna toss 'em.",
        img_url: 'https://content.instructables.com/ORIG/F8M/248F/IRHV5S0F/F8M248FIRHV5S0F.jpg?auto=webp&fit=bounds&frame=1&height=1024&width=1024',
        location_zipcode: '27516',
        category_id: 4,
        user_id: 3,
    },
    {
        product_name: 'Extension Cord',
        description: "I have an old extension cord that I just don't use much anymore. Still works just fine, but a bit of grime still on it.",
        img_url: 'https://www.lumberking.com/Data/694x463oldextensioncord.jpg?Revision=s23m&Timestamp=zXzH8G',
        location_zipcode: '27519',
        category_id: 3,
        user_id: 4,
    },
    {
        product_name: 'Pink lamp',
        description: "This lamp just doesn't fit my decor anymore so I'd like to give it to someone who'll appreciate it. Works fine!",
        img_url: 'https://pyxis.nymag.com/v1/imgs/ed9/88a/6e1649f13c89ae27e1f114ce30ba97cbeb-etsy-lamp.2x.rsocial.w600.jpg',
        location_zipcode: '27610',
        category_id: 5,
        user_id: 5,
    },
    {
        product_name: 'Measuring spoons',
        description: "A set of some basic measuring spoons. None missing - see pic.",
        img_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ4XTaqMTRw2YB4v2DZIbTuh45PlHc3amfIQ&usqp=CAU',
        location_zipcode: '27616',
        category_id: 5,
        user_id: 6,
    },
    {
        product_name: 'Dog bowls',
        description: "A pair of dog bowls for food and water. Our little best friend is off to greener fields now 😢 but we'd love for someone else to be able to make use of them.",
        img_url: 'https://www.rover.com/blog/wp-content/uploads/2021/04/bowls-3474823_1280-e1619716798509-960x540.jpg',
        location_zipcode: '27512',
        category_id: 5,
        user_id: 7,
    },
    {
        product_name: 'Old nintendo controller',
        description: "I've just found this old nintendo controller while searching through my attic but I don't have a console anymore. If you can use it you're welcome to pick it up.",
        img_url: 'https://www.lukiegames.com/assets/images/untitled3of3-042315.jpg',
        location_zipcode: '27515',
        category_id: 6,
        user_id: 1,
    },
    {
        product_name: 'Old Xbox',
        description: "My youngest son hasn't touched this for years. He just plays on his computer now. No controllers.",
        img_url: 'https://i.ebayimg.com/images/g/sDEAAOSwAP9b~XHK/s-l300.jpg',
        location_zipcode: '27890',
        category_id: 6,
        user_id: 2,
    },
    {
        product_name: 'Grey Shirt',
        description: "Doesn't fit me anymore since loosing weight 💪🏻 men's size large.",
        img_url: 'https://di2ponv0v5otw.cloudfront.net/posts/2019/07/24/5d3887b816105d9144a4d19f/m_5d3887cbbb22e39a20e008a1.jpg',
        location_zipcode: '27513',
        category_id: 8,
        user_id: 3,
    },
    {
        product_name: 'Light blue button down',
        description: "Men's size medium. I work from home a lot now so I don't need as many.",
        img_url: 'https://i.ebayimg.com/images/g/YpkAAOSw51lddXWU/s-l300.jpg',
        location_zipcode: '27516',
        category_id: 8,
        user_id: 4,
    },
    {
        product_name: 'Grey unisex pants',
        description: "A pair of light grey unisex pants. No issues or tears, just not my style anymore.",
        img_url: 'https://i.ebayimg.com/images/g/pF0AAOSwBP9blV2j/s-l400.jpg',
        location_zipcode: '27516',
        category_id: 8,
        user_id: 5,
    },


];

const seedProduct = () => Product.bulkCreate(productdata);

module.exports = seedProduct;