const { Product } = require('../models');

const productdata = [
    {
        product_name: 'Washer',
        description: 'Fairly old whirlpool washer that does not currently work. I do not have the time to fix it myself.',
        img_url: '/images/Assets/washer.jpg',
        location_zipcode: '27513',
        category_id: 1,
        user_id: 1,
    },
    {
        product_name: 'stove top',
        description: 'Used stove top. In working condition, no longer have need for it.',
        img_url: '/images/Assets/stove-top.jpg',
        location_zipcode: '27607',
        category_id: 1,
        user_id: 2,
    },
    {
        product_name: 'Old A/C Unit',
        description: 'Got an old Amana A/C unit that is still in working condition.',
        img_url: 'https://cd5a26cb38e2f692acf4-1755b9e4a9778d68267568d15a55e9ec.ssl.cf2.rackcdn.com/5539bca8f3/55-1.jpg',
        location_zipcode: '27523',
        category_id: 1,
        user_id: 1,
    },
    {
        product_name: 'Radiators',
        description: 'These old radiators are just sitting in my attic. Someone come get them!',
        img_url: 'https://cdn.vox-cdn.com/thumbor/MogVo8k0wfOlSjlejnm-bnQuB-o=/0x0:1899x918/1200x800/filters:focal(798x308:1100x610)/cdn.vox-cdn.com/uploads/chorus_image/image/65889550/vintage_radiators_x_banner.0.jpg',
        location_zipcode: '27607',
        category_id: 1,
        user_id: 2,
    },
    {
        product_name: 'Couch',
        description: 'Older family couch. Has a little wear and tear, but can easily be repurposed.',
        img_url: '/images/Assets/couch.jpg',
        location_zipcode: '27604',
        category_id: 2,
        user_id: 3,
    },
    {
        product_name: 'Side table',
        description: 'Damaged side table with scuff marks',
        img_url: '/images/Assets/side-table.jpg',
        location_zipcode: '27604',
        category_id: 2,
        user_id: 1,
    },
    {
        product_name: 'Old chairs',
        description: 'These older chairs just need some love to look brand new and unique.',
        img_url: 'https://wisebread-killeracesmedia.netdna-ssl.com/files/fruganomics/imagecache/605x340/blog-images/chairs-5252078-small.jpg',
        location_zipcode: '27877',
        category_id: 2,
        user_id: 3,
    },
    {
        product_name: 'Gaming Chair',
        description: 'My daughter used to use this old gaming chair in high-school, but since she moved off to college and since we are trying to turn her room into an office, I dont see any need for it.',
        img_url: 'https://www.nfm.com/dw/image/v2/BDFM_PRD/on/demandware.static/-/Sites-nfm-master-catalog/default/dw4d406f23/images/053/35/53350070-1.jpg?sw=365&sh=365&sm=fit',
        location_zipcode: '28334',
        category_id: 2,
        user_id: 1,
    },
    {
        product_name: 'Gameboy Color',
        description: 'Old gameboy color found in my sons room. Still works, but has no games.',
        img_url: '/images/Assets/gameboy.jpg',
        location_zipcode: '27602',
        category_id: 3,
        user_id: 2,
    },
    {
        product_name: 'Old TV',
        description: 'I have an old TV with a large back, one of the really old ones.',
        img_url: '/images/Assets/old-tv.jpg',
        location_zipcode: '27607',
        category_id: 3,
        user_id: 3,
    },
    {
        product_name: 'Assortment of video gaming consoles',
        description: 'This is a collection of gaming consoles that my husband has had since he was a teenager, but he never plays with them and they just collect dust so I am sure that he will not mind me getting rid of some junk.',
        img_url: 'https://www.realgear.net/wp-content/uploads/2017/08/retro-gaming-consoles-scaled.jpg',
        location_zipcode: '27223',
        category_id: 3,
        user_id: 2,
    },
    {
        product_name: 'Portable DVD player',
        description: 'Bought this portable dvd player for my grandson for christmas last year, but never uses it and I dont know why. First come first serve.',
        img_url: 'https://u-mercari-images.mercdn.net/photos/m98210249719_1.jpg?1612654033',
        location_zipcode: '27607',
        category_id: 3,
        user_id: 3,
    },
    {
        product_name: 'Rusted Screwdrivers',
        description: 'Tin Can full of rusty screwdrivers that are no longer being used.',
        img_url: 'https://i.ytimg.com/vi/xNukg6c93vg/maxresdefault.jpg',
        location_zipcode: '27560',
        category_id: 4,
        user_id: 2,
    },
    {
        product_name: 'Axe',
        description: 'Wooden handle axe that I no longer need.',
        img_url: '/images/Assets/axe.jpg',
        location_zipcode: '27616',
        category_id: 4,
        user_id: 1,
    },
    {
        product_name: 'Old Power Saw',
        description: 'Got this old power saw that I want to get rid of since I bought a new one. Still works just remember to wear safety goggles!',
        img_url: 'https://diy.sndimg.com/content/dam/images/diy/fullset/2011/8/12/0/Original_Old-Circular-Saw_s4x3.jpg.rend.hgtvcom.1280.960.suffix/1420874850655.jpeg',
        location_zipcode: '27560',
        category_id: 4,
        user_id: 2,
    },
    {
        product_name: 'Power Drills',
        description: 'Dont need these old drills anymore. If they arent gone in 1 week then Im just gonna toss em.',
        img_url: 'https://content.instructables.com/ORIG/F8M/248F/IRHV5S0F/F8M248FIRHV5S0F.jpg?auto=webp&fit=bounds&frame=1&height=1024&width=1024',
        location_zipcode: '27616',
        category_id: 4,
        user_id: 1,
    },

];

const seedProduct = () => Product.bulkCreate(productdata);

module.exports = seedProduct;